# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0enotifier.proto\x12\x08notifier"V\n\tSendEvent\x12\x10\n\x08\x63onsumer\x18\x01 \x01(\t\x12\x15\n\rtemplate_type\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t"+\n\x08Response\x12\x0e\n\x06sended\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"/\n\x0c\x44\x61taReceiver\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\tisSuccess\x18\x02 \x01(\x08"U\n\nHeathCheck\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\t"/\n\x0eSendHelthCheck\x12\x0c\n\x04ping\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2}\n\x08Notifier\x12@\n\nHeathcheck\x12\x18.notifier.SendHelthCheck\x1a\x14.notifier.HeathCheck(\x01\x30\x01\x12/\n\x04Send\x12\x13.notifier.SendEvent\x1a\x12.notifier.ResponseB\x06Z\x04./pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "notifier_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\004./pb"
    _globals["_SENDEVENT"]._serialized_start = 28
    _globals["_SENDEVENT"]._serialized_end = 114
    _globals["_RESPONSE"]._serialized_start = 116
    _globals["_RESPONSE"]._serialized_end = 159
    _globals["_DATARECEIVER"]._serialized_start = 161
    _globals["_DATARECEIVER"]._serialized_end = 208
    _globals["_HEATHCHECK"]._serialized_start = 210
    _globals["_HEATHCHECK"]._serialized_end = 295
    _globals["_SENDHELTHCHECK"]._serialized_start = 297
    _globals["_SENDHELTHCHECK"]._serialized_end = 344
    _globals["_NOTIFIER"]._serialized_start = 346
    _globals["_NOTIFIER"]._serialized_end = 471
# @@protoc_insertion_point(module_scope)
