# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notifier_pb2 as notifier__pb2


class NotifierStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heathcheck = channel.unary_unary(
                '/notifier.NotifierStream/Heathcheck',
                request_serializer=notifier__pb2.HeathCheck.SerializeToString,
                response_deserializer=notifier__pb2.HeathCheck.FromString,
                )
        self.Send = channel.stream_unary(
                '/notifier.NotifierStream/Send',
                request_serializer=notifier__pb2.SendEvent.SerializeToString,
                response_deserializer=notifier__pb2.Response.FromString,
                )


class NotifierStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heathcheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifierStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heathcheck': grpc.unary_unary_rpc_method_handler(
                    servicer.Heathcheck,
                    request_deserializer=notifier__pb2.HeathCheck.FromString,
                    response_serializer=notifier__pb2.HeathCheck.SerializeToString,
            ),
            'Send': grpc.stream_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=notifier__pb2.SendEvent.FromString,
                    response_serializer=notifier__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notifier.NotifierStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotifierStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heathcheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifier.NotifierStream/Heathcheck',
            notifier__pb2.HeathCheck.SerializeToString,
            notifier__pb2.HeathCheck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Send(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/notifier.NotifierStream/Send',
            notifier__pb2.SendEvent.SerializeToString,
            notifier__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
